import numpy as np
from file_loading import file_loader
import math
from pprint import pprint


class Cluster:

    def __init__(self,data,similariteMatrix,tradeOff,numberClusters,convergence,realName,typesName,matType):
        self.loader = file_loader()
        self.data = self.loader.load_file(data,True)
        self.similarite = self.loader.load_file(similariteMatrix,True)
        self.matType = self.loader.load_file(matType,True)
        self.typesName = self.loader.load_file(typesName,False,dic= True)
        self.names = self.loader.load_file(realName)
        self.T = tradeOff
        self.Nc = numberClusters
        self.c = convergence
        self.N = len(self.data)
        self.pi = 1.0/float(self.N)
        self.initialization()
        self.learn()
        print("Fin du clustering !")
        '''for i in range(self.N):
            print(sum(self.Pci[i]))'''
        self.generateClusters()

    #return the domain of the compagnie
    def associate(self,tab):
        tmp = [str(i) for i in range(len(tab)) if int(tab[i])==1]
        cle = ''.join(tmp)
        print(cle)

    def generateClusters(self):
        self.association = {}
        for i in range(self.Nc):
            self.association[i] = []
        tab = range(self.Nc)
        for i in range(self.N):
            classe  = np.random.choice(tab,p=self.Pci[i])
            self.association[classe].append(self.names[i])
            self.associate(self.matType[i])
        print("Association :")
        #pprint(self.association)

    def initialization(self):
        self.Pci = []
        for i in range(self.N):
            self.Pci= self.Pci + list(np.random.dirichlet(np.ones(self.Nc),size=1))
        self.m =0
        print("Taille de la matrice PCmi ",len(self.Pci))
        print("Longueur : ",len(self.Pci[0]))
        self.PciNew = list(np.zeros((self.N,self.Nc)))
        print("Taille de la matrice PciNew ",len(self.PciNew))
        print("Longueur : ",len(self.PciNew[0]))

    #return P(m)(C)
    def get_pc(self,C):
        result = 0.0
        for i in range(self.N):
            result+=self.Pci[i][C] * self.pi
        return result

    def getSimC(self,C):
        return 0

    #wrong value  : self.similarite[element][C]
    def calculateNewPci(self,element):
        for C in range(self.Nc):
            subCalcul = self.T*(2.0*float(self.similarite[element][C])-self.getSimC(C))
            self.PciNew[element][C]= self.get_pc(C)*math.exp(subCalcul)
             

    def majPci(self,element):
        oldvalue = float(sum(self.PciNew[element]))
        for C in range(self.Nc):
            self.PciNew[element][C] = self.PciNew[element][C]/oldvalue
   
    def should_stop(self):
        stop = True
        for i in range(self.N):
            for C in range(self.Nc):
                if(self.PciNew[i][C] - self.Pci[i][C] > self.c):
                    stop = False
        return stop

    def learn(self):
        while(True):
            for i in range(self.N):
                self.calculateNewPci(i)
                self.majPci(i)
                self.m +=1
            if(self.should_stop()):
                print("L'algorithme a converge en ",self.m)
                self.Pci = self.PciNew[:]
                return
            self.Pci = self.PciNew[:]
        print("L'algo n'a pas converge ")


cluster = Cluster("data/sp500_data.d","mi_sp500.d",20,35,1,"data/sp500_names.d","data/sp500_TypeNames.d","data/sp500_matType.d")


'''result:

{0: [u'Johnson Controls [JCI]',
     u'Verizon Communications [VZ]',
     u'Knight-Ridder Inc. [KRI]',
     u'Freeport-McMoran Cp & Gld [FCX]',
     u'Omnicom Group [OMC]',
     u'Prudential Financial [PRU]',
     u'General Motors [GM]',
     u'Cummins  Inc. [CMI]',
     u'Danaher Corp. [DHR]',
     u'Zions Bancorp [ZION]',
     u'AutoNation  Inc. [AN]',
     u'Stanley Works [SWK]',
     u'ITT Industries  Inc. [ITT]',
     u'Thomas & Betts [TNB]',
     u'Janus Capital Group [JNS]',
     u'Pitney-Bowes [PBI]',
     u'KeyCorp [KEY]',
     u'AmerisourceBergen Corp. [ABC]',
     u'Ford Motor [F]',
     u'McCormick & Co. [MKC]',
     u'Textron Inc. [TXT]',
     u'Kinder Morgan [KMI]',
     u'PACCAR Inc. [PCAR]',
     u'Goldman Sachs Group [GS]',
     u'American Standard [ASD]',
     u'Eaton Corp. [ETN]',
     u'Leggett & Platt [LEG]',
     u'BellSouth [BLS]',
     u'SouthTrust Corp. [SOTR]',
     u'Dover Corp. [DOV]',
     u'SunTrust Banks [STI]',
     u'Black & Decker Corp. [BDK]',
     u'Sigma-Aldrich [SIAL]',
     u'Wells Fargo [WFC]',
     u'Caterpillar Inc. [CAT]',
     u'Boeing Company [BA]',
     u'M&T Bank Corp. [MTB]',
     u'Johnson & Johnson [JNJ]',
     u'Parker-Hannifin [PH]',
     u'Wachovia Corp. (New) [WB]',
     u'Countrywide Financial Corp. [CFC]',
     u'Snap-On Inc. [SNA]',
     u'Chiron Corp. [CHIR]',
     u'Emerson Electric [EMR]',
     u'Regions Financial Corp. [RF]',
     u'Caremark Rx [CMX]',
     u'Torchmark Corp. [TMK]',
     u'3M Company [MMM]',
     u'Illinois Tool Works [ITW]',
     u'Crane Company [CR]',
     u'BB&T Corporation [BBT]',
     u'Comerica Inc. [CMA]',
     u'Medtronic Inc. [MDT]'],
 1: [u'Burlington Northern Santa Fe C [BNI]',
     u"Marriott Int'l. [MAR]",
     u'Federal Home Loan Mtg. [FRE]',
     u'Compuware Corp. [CPWR]',
     u'ConocoPhillips [COP]',
     u'Carnival Corp. [CCL]',
     u'Pepsi Bottling Group [PBG]',
     u'Bausch & Lomb [BOL]',
     u'Norfolk Southern Corp. [NSC]',
     u'Amgen [AMGN]',
     u'RJ Reynolds Tobacco [RJR]',
     u'Tenet Healthcare Corp. [THC]',
     u'Walt Disney Co. [DIS]',
     u'Avery Dennison Corp. [AVY]',
     u'Cendant Corporation [CD]',
     u'Health Management Assoc. [HMA]',
     u'Union Pacific [UNP]',
     u'Baxter International Inc. [BAX]',
     u'MBNA Corp. [KRB]',
     u'Walgreen Co. [WAG]',
     u'Brunswick Corp. [BC]',
     u'Gap (The) [GPS]',
     u'Marsh & McLennan [MMC]',
     u'PG&E Corp. [PCG]',
     u'Dow Jones & Co. [DJ]',
     u'IMS Health Inc. [RX]',
     u'Marshall & Ilsley Corp. [MI]'],
 2: [u'Anheuser-Busch [BUD]',
     u'Kimberly-Clark [KMB]',
     u'AT&T Corp. (New) [T]',
     u'Sara Lee Corp. [SLE]',
     u'Sysco Corp. [SYY]'],
 3: [u'*** [NX]',
     u'Xerox Corp. [XRX]',
     u'*** [AIH]',
     u'Wyeth [WYE]',
     u'Delta Air Lines [DAL]'],
 4: [u'Sempra Energy [SRE]',
     u'Consolidated Edison [ED]',
     u'Newmont Mining Corp. (Hldg. Co.) [NEM]',
     u'Block H&R [HRB]',
     u'FPL Group [FPL]',
     u'Constellation Energy Group [CEG]',
     u'Peoples Energy [PGL]',
     u'Southern Co. [SO]',
     u'*** [GFR]',
     u'CINergy Corp. [CIN]',
     u'Nextel Communications [NXTL]',
     u"Edison Int'l [EIX]"],
 5: [u'Marathon Oil Corp. [MRO]',
     u'*** [SNSTA]',
     u'Sunoco.  Inc. [SUN]',
     u'ChevronTexaco Corp. [CVX]'],
 6: [u'Applera Corp-Applied Biosystems Group [ABI]',
     u'General Electric [GE]',
     u'Millipore Corp. [MIL]',
     u'MedImmune Inc. [MEDI]',
     u'Forest Laboratories [FRX]',
     u'Intuit  Inc. [INTU]',
     u'Dynegy Inc. (New) Class A [DYN]',
     u'Genzyme Corp. [GENZ]'],
 7: [u'Darden Restaurants [DRI]',
     u'Yum! Brands  Inc [YUM]',
     u'HCA Inc. [HCA]',
     u'Federated Investors Inc. [FII]'],
 8: [u'Keyspan Energy [KSE]',
     u'Exelon Corp. [EXC]',
     u'Mattel  Inc. [MAT]',
     u'PPL Corp. [PPL]',
     u'Public Serv. Enterprise Inc. [PEG]',
     u'American Electric Power [AEP]',
     u'Progress Energy  Inc. [PGN]',
     u'NIKE Inc. [NKE]',
     u'Lockheed Martin Corp. [LMT]',
     u'DTE Energy Co. [DTE]',
     u'NiSource Inc. [NI]',
     u'Guidant Corp. [GDT]',
     u'Ameren Corporation [AEE]'],
 9: [u'Coca-Cola Enterprises [CCE]',
     u'Coca Cola Co. [KO]',
     u'Allegheny Energy [AYE]',
     u'ConAgra Foods  Inc. [CAG]'],
 10: [u'Humana Inc. [HUM]', u'WellPoint Health Networks [WLP]'],
 11: [u'Sun Microsystems [SUNW]',
      u'Raytheon Co. (New) [RTN]',
      u'International Game Technology [IGT]',
      u'*** [MEE]',
      u'Pinnacle West Capital [PNW]',
      u'EMC Corp. [EMC]',
      u'Calpine Corp. [CPN]'],
 12: [u'Advanced Micro Devices [AMD]',
      u'*** [MXM]',
      u'Goodyear Tire & Rubber [GT]'],
 13: [u'FIserv Inc. [FISV]',
      u'Hilton Hotels [HLT]',
      u'Dell Inc. [DELL]',
      u'Cisco Systems [CSCO]',
      u'Merrill Lynch [MER]',
      u'Power-One Inc. [PWER]',
      u'Sanmina-SCI Corp. [SANM]',
      u'FedEx Corporation [FDX]',
      u'MGIC Investment [MTG]',
      u'Vulcan Materials [VMC]',
      u'Apple Computer [AAPL]',
      u'T. Rowe Price Group [TROW]',
      u'NICOR Inc. [GAS]',
      u'Harley-Davidson [HDI]',
      u'Huntington Bancshares [HBAN]',
      u'First Data [FDC]',
      u'General Dynamics [GD]',
      u'Cintas Corporation [CTAS]',
      u'Colgate-Palmolive [CL]',
      u'Franklin Resources [BEN]',
      u'Allegheny Technologies Inc [ATI]',
      u'Equifax Inc. [EFX]',
      u'J.P. Morgan Chase & Co. [JPM]',
      u'Visteon Corp. [VC]',
      u'SunGard Data Systems [SDS]',
      u'Paychex Inc. [PAYX]',
      u'American Power Conversion [APCC]',
      u'Convergys Corp. [CVG]',
      u'Allergan  Inc. [AGN]',
      u'Bank of New York [BK]'],
 14: [u'Deere & Co. [DE]',
      u'St Jude Medical [STJ]',
      u'Safeway Inc. [SWY]',
      u'Waters Corporation [WAT]',
      u'Ingersoll-Rand Co. Ltd. [IR]',
      u'TXU Corp. [TXU]',
      u'Maytag Corp. [MYG]',
      u'Xcel Energy Inc [XEL]',
      u'Avon Products [AVP]',
      u'Schering-Plough [SGP]',
      u'Fortune Brands  Inc. [FO]',
      u'Heinz (H.J.) [HNZ]',
      u'Gillette Co. [G]'],
 15: [u'Ryder System [R]',
      u'Meredith Corp. [MDP]',
      u'Duke Energy [DUK]',
      u'Robert Half International [RHI]',
      u'Dominion Resources [D]',
      u'Rockwell Collins [COL]',
      u'PNC Bank Corp. [PNC]',
      u"Albertson's [ABS]"],
 16: [u'Parametric Technology [PMTC]',
      u'Symbol Technologies [SBL]',
      u'Avaya Inc. [AV]',
      u'CMS Energy [CMS]'],
 17: [u'Quest Diagnostics [DGX]',
      u'Anthem  Inc. [ATH]',
      u'Zimmer Holdings [ZMH]',
      u'Bristol-Myers Squibb [BMY]'],
 18: [u'Bed Bath & Beyond [BBBY]',
      u'Costco Co. [COST]',
      u'Clorox Co. [CLX]',
      u'United States Steel Corp. [X]',
      u'Penney (J.C.) [JCP]',
      u'TJX Companies Inc. [TJX]',
      u'PepsiCo Inc. [PEP]',
      u'Centex Corp. [CTX]',
      u'AES Corp. [AES]',
      u'Symantec Corp. [SYMC]',
      u'Pulte Homes  Inc. [PHM]',
      u'Family Dollar Stores [FDO]',
      u'Tribune Co. [TRB]',
      u'Capital One Financial [COF]',
      u'Target Corp. [TGT]',
      u'Best Buy Co.  Inc. [BBY]',
      u'Staples Inc. [SPLS]',
      u'Dollar General [DG]',
      u'Comcast Corp. [CMCSA]',
      u'Watson Pharmaceuticals [WPI]',
      u'Tiffany & Co. [TIF]',
      u'Nordstrom [JWN]',
      u'Starwood Hotels & Resorts [HOT]',
      u'Golden West Financial [GDW]',
      u'New York Times Cl. A [NYT]',
      u'Sears  Roebuck & Co. [S]',
      u'Masco Corp. [MAS]',
      u"Lowe's Cos. [LOW]",
      u'May Dept. Stores [MAY]',
      u'Wal-Mart Stores [WMT]',
      u'Limited Brands  Inc. [LTD]',
      u'Apollo Group [APOL]',
      u'Kellogg Co. [K]',
      u'Home Depot [HD]',
      u'Office Depot [ODP]'],
 19: [u'Loews Corp. [LTR]',
      u'SAFECO Corp. [SAFC]',
      u'Aon Corp. [AOC]',
      u'Altria Group  Inc. [MO]',
      u'UST Inc. [UST]',
      u'Biomet  Inc. [BMET]',
      u'U.S. Bancorp [USB]',
      u'Mellon Bank Corp. [MEL]',
      u'CIGNA Corp. [CI]',
      u'Lincoln National [LNC]',
      u'National City Corp. [NCC]',
      u'Dana Corp. [DCN]',
      u'Sabre Holding Corp. [TSG]',
      u'Hasbro Inc. [HAS]',
      u'Pfizer  Inc. [PFE]',
      u'Principal Financial Group [PFG]',
      u'Plum Creek Timber Co. [PCL]',
      u'Gateway Inc. [GTW]',
      u'International Flav/Frag [IFF]',
      u'Union Planters Corporation [UPC]',
      u'AmSouth Bancorporation [ASO]',
      u'Synovus Financial [SNV]',
      u'Washington Mutual [WM]',
      u'PerkinElmer [PKI]',
      u'United Parcel Service [UPS]',
      u'Hartford Financial Svc.Gp. [HIG]',
      u'Louisiana Pacific [LPX]',
      u'Bank of America Corp. [BAC]',
      u'Exxon Mobil Corp. [XOM]',
      u'SBC Communications Inc. [SBC]',
      u"American Int'l. Group [AIG]",
      u'North Fork Bancorporation [NFB]',
      u'Lehman Bros. [LEH]',
      u'Citigroup Inc. [C]',
      u'Allstate Corp. [ALL]',
      u'Hershey Foods [HSY]',
      u'FirstEnergy Corp. [FE]',
      u'Jefferson-Pilot [JP]',
      u'American Express [AXP]',
      u'Monsanto Co. [MON]',
      u'McKesson Corp. (New) [MCK]'],
 20: [u'*** [VTR]', u'*** [HMT]'],
 21: [u'Ambac Financial Group [ABK]',
      u'MetLife Inc. [MET]',
      u'MBIA Inc. [MBI]',
      u'Bard (C.R.) Inc. [BCR]',
      u'XL Capital [XL]',
      u'Charles Schwab [SCH]',
      u'Federated Dept. Stores [FD]',
      u'Chubb Corp. [CB]',
      u'Dillard Inc. [DDS]',
      u'SLM Corporation [SLM]',
      u'*** [SZ]',
      u'Cincinnati Financial [CINF]',
      u"Harrah's Entertainment [HET]",
      u'Merck & Co. [MRK]',
      u'Goodrich Corporation [GR]',
      u'Bear Stearns Cos. [BSC]',
      u'UnumProvident Corp. [UNM]',
      u'ACE Limited [ACE]',
      u'Circuit City Group [CC]'],
 22: [u'Great Lakes Chemical [GLK]',
      u'King Pharmaceuticals [KG]',
      u'Tyco International [TYC]',
      u'Deluxe Corp. [DLX]',
      u'Procter & Gamble [PG]',
      u'Worthington Ind. [WOR]',
      u'Automatic Data Processing Inc. [ADP]',
      u'Providian Financial Corp. [PVN]',
      u'Delphi Corporation [DPH]',
      u'Praxair  Inc. [PX]',
      u'Ashland Inc. [ASH]',
      u'Charter One Financial [CF]',
      u'Qwest Communications Int [Q]',
      u'Engelhard Corp. [EC]',
      u'Morgan Stanley [MWD]',
      u'Clear Channel Communications [CCU]',
      u'Eastman Kodak [EK]',
      u'Lilly (Eli) & Co. [LLY]',
      u'AutoZone Inc. [AZO]',
      u'Phelps Dodge [PD]',
      u'Sherwin-Williams [SHW]'],
 23: [u'Dow Chemical [DOW]',
      u'General Mills [GIS]',
      u'Eastman Chemical [EMN]',
      u'AFLAC Corporation [AFL]',
      u'E*Trade Financial Corp. [ET]',
      u'Whirlpool Corp. [WHR]',
      u'Motorola Inc. [MOT]',
      u'Gannett Co. [GCI]',
      u"Honeywell Int'l Inc. [HON]",
      u'Sealed Air Corp.(New) [SEE]',
      u'Affiliated Computer [ACS]',
      u'Electronic Data Systems [EDS]',
      u'Nucor Corp. [NUE]',
      u'Mylan Laboratories [MYL]',
      u'Progressive Corp. [PGR]',
      u'Du Pont (E.I.) [DD]',
      u"Wendy's International [WEN]",
      u'Ecolab Inc. [ECL]',
      u'Archer-Daniels-Midland [ADM]',
      u'Air Products & Chemicals [APD]',
      u'Corning Inc. [GLW]',
      u'Rohm & Haas [ROH]',
      u'PPG Industries [PPG]',
      u'Abbott Labs [ABT]'],
 24: [u'Stryker Corp. [SYK]',
      u'Cardinal Health  Inc. [CAH]',
      u'Becton  Dickinson [BDX]',
      u'Boston Scientific [BSX]',
      u'Aetna Inc. (New) [AET]',
      u'Big Lots  Inc. [BLI]'],
 25: [u'*** [NXL]',
      u'Equity Office Properties [EOP]',
      u"Apartment Investment & Mgmt'A' [AIV]",
      u'Simon Property Group  Inc [SPG]',
      u'Equity Residential [EQR]'],
 26: [u'Texas Instruments [TXN]',
      u'Electronic Arts [ERTS]',
      u'Micron Technology [MU]',
      u'BMC Software [BMC]',
      u'NVIDIA Corp. [NVDA]',
      u'Intel Corp. [INTC]',
      u'Fluor Corp. (New) [FLR]',
      u'Altera Corp. [ALTR]',
      u'McGraw-Hill [MHP]',
      u'eBay Inc. [EBAY]',
      u'Analog Devices [ADI]',
      u'CVS Corp. [CVS]',
      u'Mercury Interactive [MERQ]',
      u'KB Home [KBH]',
      u'PeopleSoft Inc. [PSFT]',
      u'AT&T Wireless Services [AWE]',
      u'Starbucks Corp. [SBUX]',
      u"Kohl's Corp. [KSS]",
      u'Tektronix Inc. [TEK]',
      u'Express Scripts [ESRX]',
      u'Pall Corp. [PLL]',
      u'Solectron [SLR]',
      u'Adobe Systems [ADBE]',
      u'Monster Worldwide [MNST]',
      u'PMC-Sierra Inc. [PMCS]',
      u'CIENA Corp. [CIEN]',
      u'Maxim Integrated Prod [MXIM]',
      u'Oracle Corp. [ORCL]',
      u'National Semiconductor [NSM]',
      u'Thermo Electron [TMO]',
      u'ADC Telecommunications [ADCT]',
      u'RadioShack Corp [RSH]',
      u'QUALCOMM Inc. [QCOM]',
      u'Computer Sciences Corp. [CSC]',
      u'Linear Technology Corp. [LLTC]',
      u'Andrew Corp. [ANDW]',
      u'Computer Associates Intl. [CA]',
      u'Grainger (W.W.) Inc. [GWW]'],
 27: [u'*** [VVI]',
      u"McDonald's Corp. [MCD]",
      u'CenterPoint Energy [CNP]',
      u'Allied Waste Industries [AW]'],
 28: [u'BJ Services [BJS]',
      u'*** [TWW]',
      u'Rowan Cos. [RDC]',
      u'Valero Energy [VLO]',
      u'Nabors Industries Ltd. [NBR]',
      u'Burlington Resources [BR]',
      u'Amerada Hess [AHC]',
      u'Transocean Inc. [RIG]',
      u'Anadarko Petroleum [APC]',
      u'Schlumberger Ltd. [SLB]',
      u'Baker Hughes [BHI]',
      u'Devon Energy Corp. [DVN]'],
 29: [u'Teradyne Inc. [TER]',
      u'QLogic Corp. [QLGC]',
      u'*** [SNS]',
      u'LSI Logic [LSI]',
      u'Hewlett-Packard [HPQ]',
      u"Lexmark Int'l Inc [LXK]",
      u'Fifth Third Bancorp [FITB]',
      u'El Paso Corp. [EP]',
      u'Applied Materials [AMAT]',
      u'Citrix Systems [CTXS]',
      u'Novellus Systems [NVLS]',
      u'Broadcom Corporation [BRCM]',
      u'Xilinx  Inc [XLNX]',
      u'Comverse Technology [CMVT]',
      u'Network Appliance [NTAP]',
      u'Interpublic Group [IPG]',
      u'Jabil Circuit [JBL]',
      u'Agilent Technologies [A]',
      u'BIOGEN IDEC Inc. [BIIB]',
      u'Northern Trust Corp. [NTRS]',
      u'KLA-Tencor Corp. [KLAC]',
      u'TECO Energy [TE]'],
 30: [u"Moody's Corp [MCO]",
      u'Kroger Co. [KR]',
      u'State Street Corp. [STT]',
      u'Coors (Adolph) [RKY]',
      u'International Bus. Machines [IBM]',
      u'Campbell Soup [CPB]',
      u'Toys R Us  Inc. [TOY]'],
 31: [u'Tellabs  Inc. [TLAB]',
      u'Waste Management Inc. [WMI]',
      u'Citizens Communications [CZN]',
      u'Hercules  Inc. [HPC]',
      u'Rockwell Automation  Inc. [ROK]',
      u'Molex Inc. [MOLX]',
      u'ProLogis [PLD]',
      u'Yahoo Inc. [YHOO]',
      u'Scientific-Atlanta [SFA]',
      u'Applied Micro Circuits [AMCC]',
      u'JDS Uniphase Corp [JDSU]',
      u'Williams Cos. [WMB]',
      u'Siebel  Systems Inc [SEBL]',
      u'*** [NT]',
      u'Liz Claiborne  Inc. [LIZ]'],
 32: [u'Ball Corp. [BLL]',
      u'V.F. Corp. [VFC]',
      u'Fannie Mae [FNM]',
      u'Entergy Corp. [ETR]',
      u'Supervalu Inc. [SVU]',
      u'Wrigley (Wm) Jr. [WWY]'],
 33: [u'Kerr-McGee [KMG]',
      u'EOG Resources [EOG]',
      u'Unocal Corp. [UCL]',
      u'Century Telephone [CTL]',
      u'Occidental Petroleum [OXY]',
      u'Apache Corp. [APA]',
      u'Winn-Dixie [WIN]',
      u'Halliburton Co. [HAL]'],
 34: [u'Boise Cascade [BCC]',
      u'Autodesk  Inc. [ADSK]',
      u'Northrop Grumman Corp. [NOC]',
      u'Cooper Tire & Rubber [CTB]',
      u'Jones Apparel Group [JNY]',
      u'Pactiv Corp. [PTV]',
      u'United Technologies [UTX]',
      u'Univision Communications [UVN]',
      u'MeadWestvaco Corporation [MWV]',
      u'Navistar International Corp. [NAV]',
      u'Genuine Parts [GPC]',
      u'Manor Care Inc. [HCR]',
      u'ALLTEL Corp. [AT]',
      u'Bank One Corp. [ONE]',
      u'Cooper Industries  Ltd. [CBE]',
      u'NCR Corp. [NCR]',
      u'Alcoa Inc [AA]',
      u'Time Warner Inc. [TWX]',
      u'Southwest Airlines [LUV]',
      u'Bemis Company [BMS]',
      u'Unisys Corp. [UIS]',
      u'CSX Corp. [CSX]',
      u'International Paper [IP]',
      u'Georgia-Pacific Group [GP]',
      u'Temple-Inland [TIN]',
      u'Weyerhaeuser Corp. [WY]',
      u'Newell Rubbermaid Co. [NWL]',
      u'Sprint Corp. FON [FON]',
      u'Microsoft Corp. [MSFT]',
      u'Lucent Technologies [LU]']}



'''
